services:
  - type: web
    name: entropy-guard
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn password_audit_lib.web:app
    autoDeploy: true
